# Generated by Django 4.2.1 on 2023-05-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
